---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: cjmulti-system

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cjmulti-controller-manager
  namespace: cjmulti-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cjmulti-leader-election-role
  namespace: cjmulti-system
rules:
  - apiGroups:
      - ""
      - coordination.k8s.io
    resources:
      - configmaps
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: cjmulti-manager-role
rules:
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs/status
    verbs:
      - get
  - apiGroups:
      - batch.tutorial.kubebuilder.io
    resources:
      - cronjobs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - batch.tutorial.kubebuilder.io
    resources:
      - cronjobs/finalizers
    verbs:
      - update
  - apiGroups:
      - batch.tutorial.kubebuilder.io
    resources:
      - cronjobs/status
    verbs:
      - get
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cjmulti-metrics-reader
rules:
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cjmulti-proxy-role
rules:
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cjmulti-leader-election-rolebinding
  namespace: cjmulti-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cjmulti-leader-election-role
subjects:
  - kind: ServiceAccount
    name: cjmulti-controller-manager
    namespace: cjmulti-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cjmulti-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cjmulti-manager-role
subjects:
  - kind: ServiceAccount
    name: cjmulti-controller-manager
    namespace: cjmulti-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cjmulti-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cjmulti-proxy-role
subjects:
  - kind: ServiceAccount
    name: cjmulti-controller-manager
    namespace: cjmulti-system
---
apiVersion: v1
data:
  controller_manager_config.yaml: |
    apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
    kind: ControllerManagerConfig
    health:
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: 127.0.0.1:8080
    webhook:
      port: 9443
    leaderElection:
      leaderElect: true
      resourceName: 80807133.tutorial.kubebuilder.io
kind: ConfigMap
metadata:
  name: cjmulti-manager-config
  namespace: cjmulti-system
---
apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
  name: cjmulti-controller-manager-metrics-service
  namespace: cjmulti-system
spec:
  ports:
    - name: https
      port: 8443
      targetPort: https
  selector:
    control-plane: controller-manager
---
apiVersion: v1
kind: Service
metadata:
  name: cjmulti-webhook-service
  namespace: cjmulti-system
spec:
  ports:
    - port: 443
      targetPort: 9443
  selector:
    control-plane: controller-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
  name: cjmulti-controller-manager
  namespace: cjmulti-system
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
        - args:
            - --secure-listen-address=0.0.0.0:8443
            - --upstream=http://127.0.0.1:8080/
            - --logtostderr=true
            - --v=10
          image: gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
          name: kube-rbac-proxy
          ports:
            - containerPort: 8443
              name: https
        - args:
            - --health-probe-bind-address=:8081
            - --metrics-bind-address=127.0.0.1:8080
            - --leader-elect
          command:
            - /manager
          image: speak2jc/conroyjobmulti:latest
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          name: manager
          ports:
            - containerPort: 9443
              name: webhook-server
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 100m
              memory: 30Mi
            requests:
              cpu: 100m
              memory: 20Mi
          securityContext:
            allowPrivilegeEscalation: false
          volumeMounts:
            - mountPath: /tmp/k8s-webhook-server/serving-certs
              name: cert
              readOnly: true
      securityContext:
        runAsNonRoot: true
      serviceAccountName: cjmulti-controller-manager
      terminationGracePeriodSeconds: 10
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: webhook-server-cert
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cjmulti-serving-cert
  namespace: cjmulti-system
spec:
  dnsNames:
    - cjmulti-webhook-service.cjmulti-system.svc
    - cjmulti-webhook-service.cjmulti-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: cjmulti-selfsigned-issuer
  secretName: webhook-server-cert
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cjmulti-selfsigned-issuer
  namespace: cjmulti-system
spec:
  selfSigned: {}
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: cjmulti-system/cjmulti-serving-cert
  name: cjmulti-mutating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: cjmulti-webhook-service
        namespace: cjmulti-system
        path: /mutate-batch-tutorial-kubebuilder-io-v1-cronjob
    failurePolicy: Fail
    name: mcronjob.kb.io
    rules:
      - apiGroups:
          - batch.tutorial.kubebuilder.io
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - cronjobs
    sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: cjmulti-system/cjmulti-serving-cert
  name: cjmulti-validating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: cjmulti-webhook-service
        namespace: cjmulti-system
        path: /validate-batch-tutorial-kubebuilder-io-v1-cronjob
    failurePolicy: Fail
    name: vcronjob.kb.io
    rules:
      - apiGroups:
          - batch.tutorial.kubebuilder.io
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - cronjobs
    sideEffects: None
